---
apiVersion: v1
kind: Service
metadata:
  name: logstash-tcp-lb
  namespace: logstash
  annotations:
    metallb.universe.tf/allow-shared-ip: 8d10d5a14b04fc7dda

spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  #loadBalancerIP: 172.23.40.142

  sessionAffinity: None
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-logstash
    app: logstash-ingress

  ports:
    - name: syslog-tcp
      port: 601
      protocol: TCP
      targetPort: 6010
