---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  project: default
  source:
    chart: kafka
    helm:
      values: |
        externalAccess:
          enabled: true
          service:
            loadBalancerIPs:
              - 172.23.40.141
        provisioning:
            enabled: true
            topics:
              - logstash-egress
              - logstash-ingress
    enabled: true
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.17.6
    path: bitnami/kafka
  ignoreDifferences:
    - kind: Service
      jsonPointers:
        - /spec/ports/0/nodePort
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
