apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  project: default
  source:
    chart: redis
    helm:
      values: |
        global:
          redis:
            password: password
        networkPolicy:
          enabled:   true
        podSecurityPolicy:
          create:    true
        rbac:
          create: true
        serviceAccount:
          create: true
    enabled: true
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.0.1
    path: bitnami/redis
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

