---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    name: operations
    namespace: default

  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: '6.9.1'
    chart: grafana
    helm:
      values: |
        serviceMonitor:
          enabled: true

        ingress:
          enabled: true
          hosts:
            - grafana.chlg.sputnik.ves.is
          tls:
            - secretName: grafana-cert
              hosts:
                - grafana.chlg.sputnik.ves.is

        plugins:
          - marcusolsson-json-datasource
          - grafana-worldmap-panel
          - natel-discrete-panel
          - grafana-polystat-panel

        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: https://fstc-m00-docker-01.vodalab.net
              isDefault: true
              jsonData:
                tlsSkipVerify: true

        admin:
          existingSecret: "grafana-creds"
          userKey: admin-user
          passwordKey: admin-password

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
