---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    name: operations
    namespace: default

  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: '6.9.1'
    chart: grafana
    helm:
      values: |
        serviceMonitor:
          enabled: true

        ingress:
          enabled: true

        admin:
          existingSecret: "grafana-creds"
          userKey: admin-user
          passwordKey: admin-password

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
