---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    name: operations
    namespace: default

  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: '6.9.1'
    chart: grafana
    helm:
      values: |
        replicas: 1
        persistence:
          enabled: true
          accessModes:
            - ReadWriteMany

        serviceMonitor:
          enabled: true

        ingress:
          enabled: true
          hosts:
            - grafana.chlg.sputnik.ves.is
          tls:
            - secretName: grafana-cert
              hosts:
                - grafana.chlg.sputnik.ves.is

        plugins:
          - marcusolsson-json-datasource
          - grafana-worldmap-panel
          - natel-discrete-panel
          - grafana-polystat-panel
          #  - grafana-image-renderer

        extraConfigmapMounts:
           - name: grafana-certs
             mountPath: /etc/grafana/ldap/
             configMap: grafana-certs
             readOnly: true

        grafana.ini:
          auth.ldap:
            enabled: true
            allow_sign_up: true
            config_file: /etc/grafana/ldap.toml

        ldap:
          enabled: true
          config: |- 
            [[servers]]
            host = "203.97.43.6 203.97.43.37"
            port = 636
            use_ssl = true
            start_tls = false
            ssl_skip_verify = false
            root_ca_cert = "/etc/grafana/ldap/ldap.crt"
            search_filter = "(sAMAccountName=%s)"
            search_base_dns = ["OU=MGMT_Users,DC=mgmt,DC=dmzglobal,DC=net"]
            
            [servers.attributes]
            name = "givenName"
            surname = "sn"
            username = "cn"
            email = "USERPRINCIPALNAME"
            member_of = "MEMBEROF"
            
            [[servers.group_mappings]]
            group_dn = "CN=GR_VDO_Users,OU=MGMT_Security Groups,DC=mgmt,DC=dmzglobal,DC=net"
            org_role = "Admin"
            grafana_admin = true
            org_id = 1
 
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: https://fstc-m00-docker-01.vodalab.net
                isDefault: true
                jsonData:
                  tlsSkipVerify: true
              - name: HNZC_Network
                type: influxdb
                url: https://fstc-influxdb.vodalab.net
                database: HNZC_Network
                basicAuth: true
                basicAuthUser: $INFLUXDB_USERNAME
                basicAuthPassword: $INFLUXDB_PASSWORD
                jsonData:
                  tlsSkipVerify: true
        admin:
          existingSecret: "grafana-creds"
          userKey: admin-user
          passwordKey: admin-password

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true