---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operations-logstash
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: logstash

  source:
    repoURL: https://github.com/pmackey2/argo-cd-test.git
    targetRevision: HEAD
    path: charts/logstash

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
