---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operations-root
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://docker.vodalab.net:8443/k8s/clusters/c-ff8zs
    namespace: default

  source:
    path: apps/
    repoURL: https://github.com/pmackey2/argo-cd-test.git
    targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
