---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operations-root
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://rke2-ops-server-1.chlg.sputnik.ves.is:6443
    namespace: default

  source:
    path: apps/
    repoURL: https://github.com/pmackey2/argo-cd-test.git
    targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
