argo-cd:
  installCRDs: false
  global:
    image:
      tag: v2.0.0
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - url: git@github.com:pmackey2/argo-cd-test.git
          name: github-ssh
          sshPrivateKeySecret:
            name: github-secret
            key: sshPrivateKey
        - url: https://github.com/pmackey2/argo-cd-test.git
          name: github-http
        - url: git@gitlab.chlg.sputnik.ves.is:sputnik/argo-cd-default.git
          name: gitlab.chlg.sputnik.ves.is
          sshPrivateKeySecret:
            name: argo-gitlab
            key: sshPrivateKey
      knownHosts:
          data:
            ssh_known_hosts: |
              gitlab.chlg.sputnik.ves.is ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGnNZhayfVMGkQ57vz4gL6/wtvk0gqB9Itz/zDJZKeARARZBII1pUJvHQfM11ZcnFeNDaotaZlwwvcI2MfZO6Ao=
              gitlab.chlg.sputnik.ves.is ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHFFaq9opJZ/5KdxzFVDJzWoZ+k6s60qTH1yXdvPGH61