---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default

  source:
    path: charts/argo-cd
    repoURL: https://gitlab.chlg.sputnik.ves.is/sputnik/argo-cd-default.git
    targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
