---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-runner
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: gitlab-runner

  source:
    chart: gitlab-runner
    helm:
      values: |
        rbac:
          create: true
          rules:
            - resources: ["pods", "secrets"]
              verbs: ["get", "list", "watch", "create", "patch", "delete"]
            - apiGroups: [""]
              resources: ["pods/exec"]
              verbs: ["create", "patch", "delete"]
          clusterWideAccess: true
          podSecurityPolicy:
            enabled: true

        gitlabUrl: https://gitlab.chlg.sputnik.ves.is/
        runnerRegistrationToken: "xBzCineHD1UBU-NN9CcS"

    enabled: true
    repoURL: https://charts.gitlab.io
    targetRevision: 0.28.0

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
