---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: prometheus

  source:
    chart: prometheus
    helm:
      values: |
        podSecurityPolicy:
          enabled: false
        pushgateway:
          enabled: false
        nodeExporter:
          enabled: false
        alertmanager:
          ingress:
            enabled: true
            hosts:
              - alertmanager.chlg.sputnik.ves.is
          persistentVolume:
            enabled: false
        server:
          ingress:
            enabled: true
            hosts:
              - prometheus.chlg.sputnik.ves.is
          persistentVolume:
            enabled: false
    enabled: true
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 13.0.2

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
