---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  source:
    path: apps/command/
    repoURL: https://github.com/pmackey2/argo-cd-test.git
    targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
