---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: teleport

  source:
    enabled: false
    path: charts/teleport-cluster
    repoURL: https://gitlab.chlg.sputnik.ves.is/sputnik/argo-cd-default.git
    targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
